/*
 * This file is generated by jOOQ.
 */
package com.getReferral.Referral.Application.jooq;


import com.getReferral.Referral.Application.jooq.tables.FlywaySchemaHistory;
import com.getReferral.Referral.Application.jooq.tables.ReferralApplications;
import com.getReferral.Referral.Application.jooq.tables.ReferralPosting;
import com.getReferral.Referral.Application.jooq.tables.Resumes;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in referral_db.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index REFERRAL_APPLICATIONS_APPLICANT_ID = Internal.createIndex(DSL.name("applicant_id"), ReferralApplications.REFERRAL_APPLICATIONS, new OrderField[] { ReferralApplications.REFERRAL_APPLICATIONS.APPLICANT_ID }, false);
    public static final Index RESUMES_APPLICANT_ID = Internal.createIndex(DSL.name("applicant_id"), Resumes.RESUMES, new OrderField[] { Resumes.RESUMES.APPLICANT_ID }, false);
    public static final Index FLYWAY_SCHEMA_HISTORY_FLYWAY_SCHEMA_HISTORY_S_IDX = Internal.createIndex(DSL.name("flyway_schema_history_s_idx"), FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, new OrderField[] { FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.SUCCESS }, false);
    public static final Index REFERRAL_APPLICATIONS_REFERRAL_POSTING_ID = Internal.createIndex(DSL.name("referral_posting_id"), ReferralApplications.REFERRAL_APPLICATIONS, new OrderField[] { ReferralApplications.REFERRAL_APPLICATIONS.REFERRAL_POSTING_ID }, false);
    public static final Index REFERRAL_APPLICATIONS_REFERRER_ID = Internal.createIndex(DSL.name("referrer_id"), ReferralApplications.REFERRAL_APPLICATIONS, new OrderField[] { ReferralApplications.REFERRAL_APPLICATIONS.REFERRER_ID }, false);
    public static final Index REFERRAL_POSTING_REFERRER_ID = Internal.createIndex(DSL.name("referrer_id"), ReferralPosting.REFERRAL_POSTING, new OrderField[] { ReferralPosting.REFERRAL_POSTING.REFERRER_ID }, false);
    public static final Index REFERRAL_APPLICATIONS_RESUME_ID = Internal.createIndex(DSL.name("resume_id"), ReferralApplications.REFERRAL_APPLICATIONS, new OrderField[] { ReferralApplications.REFERRAL_APPLICATIONS.RESUME_ID }, false);
}
