/*
 * This file is generated by jOOQ.
 */
package com.getReferral.Referral.Application.jooq;


import com.getReferral.Referral.Application.jooq.tables.Applicants;
import com.getReferral.Referral.Application.jooq.tables.FlywaySchemaHistory;
import com.getReferral.Referral.Application.jooq.tables.ReferralApplications;
import com.getReferral.Referral.Application.jooq.tables.ReferralPosting;
import com.getReferral.Referral.Application.jooq.tables.Referrer;
import com.getReferral.Referral.Application.jooq.tables.Resumes;
import com.getReferral.Referral.Application.jooq.tables.Users;
import com.getReferral.Referral.Application.jooq.tables.records.ApplicantsRecord;
import com.getReferral.Referral.Application.jooq.tables.records.FlywaySchemaHistoryRecord;
import com.getReferral.Referral.Application.jooq.tables.records.ReferralApplicationsRecord;
import com.getReferral.Referral.Application.jooq.tables.records.ReferralPostingRecord;
import com.getReferral.Referral.Application.jooq.tables.records.ReferrerRecord;
import com.getReferral.Referral.Application.jooq.tables.records.ResumesRecord;
import com.getReferral.Referral.Application.jooq.tables.records.UsersRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * referral_db.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ApplicantsRecord> KEY_APPLICANTS_PRIMARY = Internal.createUniqueKey(Applicants.APPLICANTS, DSL.name("KEY_applicants_PRIMARY"), new TableField[] { Applicants.APPLICANTS.APPLICANT_ID }, true);
    public static final UniqueKey<ApplicantsRecord> KEY_APPLICANTS_USER_ID = Internal.createUniqueKey(Applicants.APPLICANTS, DSL.name("KEY_applicants_user_id"), new TableField[] { Applicants.APPLICANTS.USER_ID }, true);
    public static final UniqueKey<FlywaySchemaHistoryRecord> KEY_FLYWAY_SCHEMA_HISTORY_PRIMARY = Internal.createUniqueKey(FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, DSL.name("KEY_flyway_schema_history_PRIMARY"), new TableField[] { FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.INSTALLED_RANK }, true);
    public static final UniqueKey<ReferralApplicationsRecord> KEY_REFERRAL_APPLICATIONS_PRIMARY = Internal.createUniqueKey(ReferralApplications.REFERRAL_APPLICATIONS, DSL.name("KEY_referral_applications_PRIMARY"), new TableField[] { ReferralApplications.REFERRAL_APPLICATIONS.REFERRAL_APPLICATION_ID }, true);
    public static final UniqueKey<ReferralPostingRecord> KEY_REFERRAL_POSTING_PRIMARY = Internal.createUniqueKey(ReferralPosting.REFERRAL_POSTING, DSL.name("KEY_referral_posting_PRIMARY"), new TableField[] { ReferralPosting.REFERRAL_POSTING.REFERRAL_POSTING_ID }, true);
    public static final UniqueKey<ReferrerRecord> KEY_REFERRER_PRIMARY = Internal.createUniqueKey(Referrer.REFERRER, DSL.name("KEY_referrer_PRIMARY"), new TableField[] { Referrer.REFERRER.REFERRER_ID }, true);
    public static final UniqueKey<ReferrerRecord> KEY_REFERRER_USER_ID = Internal.createUniqueKey(Referrer.REFERRER, DSL.name("KEY_referrer_user_id"), new TableField[] { Referrer.REFERRER.USER_ID }, true);
    public static final UniqueKey<ResumesRecord> KEY_RESUMES_PRIMARY = Internal.createUniqueKey(Resumes.RESUMES, DSL.name("KEY_resumes_PRIMARY"), new TableField[] { Resumes.RESUMES.RESUME_ID }, true);
    public static final UniqueKey<UsersRecord> KEY_USERS_PRIMARY = Internal.createUniqueKey(Users.USERS, DSL.name("KEY_users_PRIMARY"), new TableField[] { Users.USERS.USER_ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<ApplicantsRecord, UsersRecord> APPLICANTS_IBFK_1 = Internal.createForeignKey(Applicants.APPLICANTS, DSL.name("applicants_ibfk_1"), new TableField[] { Applicants.APPLICANTS.USER_ID }, Keys.KEY_USERS_PRIMARY, new TableField[] { Users.USERS.USER_ID }, true);
    public static final ForeignKey<ReferralApplicationsRecord, ApplicantsRecord> REFERRAL_APPLICATIONS_IBFK_1 = Internal.createForeignKey(ReferralApplications.REFERRAL_APPLICATIONS, DSL.name("referral_applications_ibfk_1"), new TableField[] { ReferralApplications.REFERRAL_APPLICATIONS.APPLICANT_ID }, Keys.KEY_APPLICANTS_PRIMARY, new TableField[] { Applicants.APPLICANTS.APPLICANT_ID }, true);
    public static final ForeignKey<ReferralApplicationsRecord, ReferralPostingRecord> REFERRAL_APPLICATIONS_IBFK_2 = Internal.createForeignKey(ReferralApplications.REFERRAL_APPLICATIONS, DSL.name("referral_applications_ibfk_2"), new TableField[] { ReferralApplications.REFERRAL_APPLICATIONS.REFERRAL_POSTING_ID }, Keys.KEY_REFERRAL_POSTING_PRIMARY, new TableField[] { ReferralPosting.REFERRAL_POSTING.REFERRAL_POSTING_ID }, true);
    public static final ForeignKey<ReferralApplicationsRecord, ReferrerRecord> REFERRAL_APPLICATIONS_IBFK_3 = Internal.createForeignKey(ReferralApplications.REFERRAL_APPLICATIONS, DSL.name("referral_applications_ibfk_3"), new TableField[] { ReferralApplications.REFERRAL_APPLICATIONS.REFERRER_ID }, Keys.KEY_REFERRER_PRIMARY, new TableField[] { Referrer.REFERRER.REFERRER_ID }, true);
    public static final ForeignKey<ReferralApplicationsRecord, ResumesRecord> REFERRAL_APPLICATIONS_IBFK_4 = Internal.createForeignKey(ReferralApplications.REFERRAL_APPLICATIONS, DSL.name("referral_applications_ibfk_4"), new TableField[] { ReferralApplications.REFERRAL_APPLICATIONS.RESUME_ID }, Keys.KEY_RESUMES_PRIMARY, new TableField[] { Resumes.RESUMES.RESUME_ID }, true);
    public static final ForeignKey<ReferralPostingRecord, ReferrerRecord> REFERRAL_POSTING_IBFK_1 = Internal.createForeignKey(ReferralPosting.REFERRAL_POSTING, DSL.name("referral_posting_ibfk_1"), new TableField[] { ReferralPosting.REFERRAL_POSTING.REFERRER_ID }, Keys.KEY_REFERRER_PRIMARY, new TableField[] { Referrer.REFERRER.REFERRER_ID }, true);
    public static final ForeignKey<ReferrerRecord, UsersRecord> REFERRER_IBFK_1 = Internal.createForeignKey(Referrer.REFERRER, DSL.name("referrer_ibfk_1"), new TableField[] { Referrer.REFERRER.USER_ID }, Keys.KEY_USERS_PRIMARY, new TableField[] { Users.USERS.USER_ID }, true);
    public static final ForeignKey<ResumesRecord, ApplicantsRecord> RESUMES_IBFK_1 = Internal.createForeignKey(Resumes.RESUMES, DSL.name("resumes_ibfk_1"), new TableField[] { Resumes.RESUMES.APPLICANT_ID }, Keys.KEY_APPLICANTS_PRIMARY, new TableField[] { Applicants.APPLICANTS.APPLICANT_ID }, true);
}
