/*
 * This file is generated by jOOQ.
 */
package com.getReferral.Referral.Application.jooq;


import com.getReferral.Referral.Application.jooq.tables.Applicants;
import com.getReferral.Referral.Application.jooq.tables.FlywaySchemaHistory;
import com.getReferral.Referral.Application.jooq.tables.ReferralApplications;
import com.getReferral.Referral.Application.jooq.tables.ReferralPosting;
import com.getReferral.Referral.Application.jooq.tables.Referrer;
import com.getReferral.Referral.Application.jooq.tables.Resumes;
import com.getReferral.Referral.Application.jooq.tables.Users;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ReferralDb extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>referral_db</code>
     */
    public static final ReferralDb REFERRAL_DB = new ReferralDb();

    /**
     * The table <code>referral_db.applicants</code>.
     */
    public final Applicants APPLICANTS = Applicants.APPLICANTS;

    /**
     * The table <code>referral_db.flyway_schema_history</code>.
     */
    public final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>referral_db.referral_applications</code>.
     */
    public final ReferralApplications REFERRAL_APPLICATIONS = ReferralApplications.REFERRAL_APPLICATIONS;

    /**
     * The table <code>referral_db.referral_posting</code>.
     */
    public final ReferralPosting REFERRAL_POSTING = ReferralPosting.REFERRAL_POSTING;

    /**
     * The table <code>referral_db.referrer</code>.
     */
    public final Referrer REFERRER = Referrer.REFERRER;

    /**
     * The table <code>referral_db.resumes</code>.
     */
    public final Resumes RESUMES = Resumes.RESUMES;

    /**
     * The table <code>referral_db.users</code>.
     */
    public final Users USERS = Users.USERS;

    /**
     * No further instances allowed
     */
    private ReferralDb() {
        super("referral_db", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Applicants.APPLICANTS,
            FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY,
            ReferralApplications.REFERRAL_APPLICATIONS,
            ReferralPosting.REFERRAL_POSTING,
            Referrer.REFERRER,
            Resumes.RESUMES,
            Users.USERS
        );
    }
}
