/*
 * This file is generated by jOOQ.
 */
package com.getReferral.Referral.Application.jooq;


import com.getReferral.Referral.Application.jooq.tables.Applicants;
import com.getReferral.Referral.Application.jooq.tables.FlywaySchemaHistory;
import com.getReferral.Referral.Application.jooq.tables.ReferralApplications;
import com.getReferral.Referral.Application.jooq.tables.ReferralPosting;
import com.getReferral.Referral.Application.jooq.tables.Referrer;
import com.getReferral.Referral.Application.jooq.tables.Resumes;
import com.getReferral.Referral.Application.jooq.tables.Users;


/**
 * Convenience access to all tables in referral_db.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>referral_db.applicants</code>.
     */
    public static final Applicants APPLICANTS = Applicants.APPLICANTS;

    /**
     * The table <code>referral_db.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>referral_db.referral_applications</code>.
     */
    public static final ReferralApplications REFERRAL_APPLICATIONS = ReferralApplications.REFERRAL_APPLICATIONS;

    /**
     * The table <code>referral_db.referral_posting</code>.
     */
    public static final ReferralPosting REFERRAL_POSTING = ReferralPosting.REFERRAL_POSTING;

    /**
     * The table <code>referral_db.referrer</code>.
     */
    public static final Referrer REFERRER = Referrer.REFERRER;

    /**
     * The table <code>referral_db.resumes</code>.
     */
    public static final Resumes RESUMES = Resumes.RESUMES;

    /**
     * The table <code>referral_db.users</code>.
     */
    public static final Users USERS = Users.USERS;
}
