/*
 * This file is generated by jOOQ.
 */
package com.getReferral.Referral.Application.jooq.tables.daos;


import com.getReferral.Referral.Application.jooq.tables.ReferralApplications;
import com.getReferral.Referral.Application.jooq.tables.records.ReferralApplicationsRecord;

import java.time.LocalDate;
import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Repository
public class ReferralApplicationsDao extends DAOImpl<ReferralApplicationsRecord, com.getReferral.Referral.Application.jooq.tables.pojos.ReferralApplications, Integer> {

    /**
     * Create a new ReferralApplicationsDao without any configuration
     */
    public ReferralApplicationsDao() {
        super(ReferralApplications.REFERRAL_APPLICATIONS, com.getReferral.Referral.Application.jooq.tables.pojos.ReferralApplications.class);
    }

    /**
     * Create a new ReferralApplicationsDao with an attached configuration
     */
    @Autowired
    public ReferralApplicationsDao(Configuration configuration) {
        super(ReferralApplications.REFERRAL_APPLICATIONS, com.getReferral.Referral.Application.jooq.tables.pojos.ReferralApplications.class, configuration);
    }

    @Override
    public Integer getId(com.getReferral.Referral.Application.jooq.tables.pojos.ReferralApplications object) {
        return object.getReferralApplicationId();
    }

    /**
     * Fetch records that have <code>referral_application_id BETWEEN
     * lowerInclusive AND upperInclusive</code>
     */
    public List<com.getReferral.Referral.Application.jooq.tables.pojos.ReferralApplications> fetchRangeOfReferralApplicationId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(ReferralApplications.REFERRAL_APPLICATIONS.REFERRAL_APPLICATION_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>referral_application_id IN (values)</code>
     */
    public List<com.getReferral.Referral.Application.jooq.tables.pojos.ReferralApplications> fetchByReferralApplicationId(Integer... values) {
        return fetch(ReferralApplications.REFERRAL_APPLICATIONS.REFERRAL_APPLICATION_ID, values);
    }

    /**
     * Fetch a unique record that has <code>referral_application_id =
     * value</code>
     */
    public com.getReferral.Referral.Application.jooq.tables.pojos.ReferralApplications fetchOneByReferralApplicationId(Integer value) {
        return fetchOne(ReferralApplications.REFERRAL_APPLICATIONS.REFERRAL_APPLICATION_ID, value);
    }

    /**
     * Fetch a unique record that has <code>referral_application_id =
     * value</code>
     */
    public Optional<com.getReferral.Referral.Application.jooq.tables.pojos.ReferralApplications> fetchOptionalByReferralApplicationId(Integer value) {
        return fetchOptional(ReferralApplications.REFERRAL_APPLICATIONS.REFERRAL_APPLICATION_ID, value);
    }

    /**
     * Fetch records that have <code>referral_posting_id BETWEEN lowerInclusive
     * AND upperInclusive</code>
     */
    public List<com.getReferral.Referral.Application.jooq.tables.pojos.ReferralApplications> fetchRangeOfReferralPostingId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(ReferralApplications.REFERRAL_APPLICATIONS.REFERRAL_POSTING_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>referral_posting_id IN (values)</code>
     */
    public List<com.getReferral.Referral.Application.jooq.tables.pojos.ReferralApplications> fetchByReferralPostingId(Integer... values) {
        return fetch(ReferralApplications.REFERRAL_APPLICATIONS.REFERRAL_POSTING_ID, values);
    }

    /**
     * Fetch records that have <code>referrer_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.getReferral.Referral.Application.jooq.tables.pojos.ReferralApplications> fetchRangeOfReferrerId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(ReferralApplications.REFERRAL_APPLICATIONS.REFERRER_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>referrer_id IN (values)</code>
     */
    public List<com.getReferral.Referral.Application.jooq.tables.pojos.ReferralApplications> fetchByReferrerId(Integer... values) {
        return fetch(ReferralApplications.REFERRAL_APPLICATIONS.REFERRER_ID, values);
    }

    /**
     * Fetch records that have <code>applicant_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.getReferral.Referral.Application.jooq.tables.pojos.ReferralApplications> fetchRangeOfApplicantId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(ReferralApplications.REFERRAL_APPLICATIONS.APPLICANT_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>applicant_id IN (values)</code>
     */
    public List<com.getReferral.Referral.Application.jooq.tables.pojos.ReferralApplications> fetchByApplicantId(Integer... values) {
        return fetch(ReferralApplications.REFERRAL_APPLICATIONS.APPLICANT_ID, values);
    }

    /**
     * Fetch records that have <code>resume_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.getReferral.Referral.Application.jooq.tables.pojos.ReferralApplications> fetchRangeOfResumeId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(ReferralApplications.REFERRAL_APPLICATIONS.RESUME_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>resume_id IN (values)</code>
     */
    public List<com.getReferral.Referral.Application.jooq.tables.pojos.ReferralApplications> fetchByResumeId(Integer... values) {
        return fetch(ReferralApplications.REFERRAL_APPLICATIONS.RESUME_ID, values);
    }

    /**
     * Fetch records that have <code>applied_date BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.getReferral.Referral.Application.jooq.tables.pojos.ReferralApplications> fetchRangeOfAppliedDate(LocalDate lowerInclusive, LocalDate upperInclusive) {
        return fetchRange(ReferralApplications.REFERRAL_APPLICATIONS.APPLIED_DATE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>applied_date IN (values)</code>
     */
    public List<com.getReferral.Referral.Application.jooq.tables.pojos.ReferralApplications> fetchByAppliedDate(LocalDate... values) {
        return fetch(ReferralApplications.REFERRAL_APPLICATIONS.APPLIED_DATE, values);
    }

    /**
     * Fetch records that have <code>status BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.getReferral.Referral.Application.jooq.tables.pojos.ReferralApplications> fetchRangeOfStatus(String lowerInclusive, String upperInclusive) {
        return fetchRange(ReferralApplications.REFERRAL_APPLICATIONS.STATUS, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>status IN (values)</code>
     */
    public List<com.getReferral.Referral.Application.jooq.tables.pojos.ReferralApplications> fetchByStatus(String... values) {
        return fetch(ReferralApplications.REFERRAL_APPLICATIONS.STATUS, values);
    }
}
