/*
 * This file is generated by jOOQ.
 */
package com.getReferral.Referral.Application.jooq.tables.interfaces;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public interface IApplicants extends Serializable {

    /**
     * Setter for <code>referral_db.applicants.applicant_id</code>.
     */
    public void setApplicantId(Integer value);

    /**
     * Getter for <code>referral_db.applicants.applicant_id</code>.
     */
    public Integer getApplicantId();

    /**
     * Setter for <code>referral_db.applicants.user_id</code>.
     */
    public void setUserId(Integer value);

    /**
     * Getter for <code>referral_db.applicants.user_id</code>.
     */
    public Integer getUserId();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common
     * interface IApplicants
     */
    public void from(IApplicants from);

    /**
     * Copy data into another generated Record/POJO implementing the common
     * interface IApplicants
     */
    public <E extends IApplicants> E into(E into);
}
