/*
 * This file is generated by jOOQ.
 */
package com.getReferral.Referral.Application.jooq.tables.interfaces;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public interface IReferrer extends Serializable {

    /**
     * Setter for <code>referral_db.referrer.referrer_id</code>.
     */
    public void setReferrerId(Integer value);

    /**
     * Getter for <code>referral_db.referrer.referrer_id</code>.
     */
    public Integer getReferrerId();

    /**
     * Setter for <code>referral_db.referrer.user_id</code>.
     */
    public void setUserId(Integer value);

    /**
     * Getter for <code>referral_db.referrer.user_id</code>.
     */
    public Integer getUserId();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common
     * interface IReferrer
     */
    public void from(IReferrer from);

    /**
     * Copy data into another generated Record/POJO implementing the common
     * interface IReferrer
     */
    public <E extends IReferrer> E into(E into);
}
