/*
 * This file is generated by jOOQ.
 */
package com.getReferral.Referral.Application.jooq.tables.interfaces;


import java.io.Serializable;
import java.math.BigDecimal;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public interface IResumes extends Serializable {

    /**
     * Setter for <code>referral_db.resumes.resume_id</code>.
     */
    public void setResumeId(Integer value);

    /**
     * Getter for <code>referral_db.resumes.resume_id</code>.
     */
    public Integer getResumeId();

    /**
     * Setter for <code>referral_db.resumes.applicant_id</code>.
     */
    public void setApplicantId(Integer value);

    /**
     * Getter for <code>referral_db.resumes.applicant_id</code>.
     */
    public Integer getApplicantId();

    /**
     * Setter for <code>referral_db.resumes.resume_name</code>.
     */
    public void setResumeName(String value);

    /**
     * Getter for <code>referral_db.resumes.resume_name</code>.
     */
    public String getResumeName();

    /**
     * Setter for <code>referral_db.resumes.branch</code>.
     */
    public void setBranch(String value);

    /**
     * Getter for <code>referral_db.resumes.branch</code>.
     */
    public String getBranch();

    /**
     * Setter for <code>referral_db.resumes.passout_yr</code>.
     */
    public void setPassoutYr(Integer value);

    /**
     * Getter for <code>referral_db.resumes.passout_yr</code>.
     */
    public Integer getPassoutYr();

    /**
     * Setter for <code>referral_db.resumes.exp_duration</code>.
     */
    public void setExpDuration(BigDecimal value);

    /**
     * Getter for <code>referral_db.resumes.exp_duration</code>.
     */
    public BigDecimal getExpDuration();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common
     * interface IResumes
     */
    public void from(IResumes from);

    /**
     * Copy data into another generated Record/POJO implementing the common
     * interface IResumes
     */
    public <E extends IResumes> E into(E into);
}
