/*
 * This file is generated by jOOQ.
 */
package com.getReferral.Referral.Application.jooq.tables.interfaces;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public interface IUsers extends Serializable {

    /**
     * Setter for <code>referral_db.users.user_id</code>.
     */
    public void setUserId(Integer value);

    /**
     * Getter for <code>referral_db.users.user_id</code>.
     */
    public Integer getUserId();

    /**
     * Setter for <code>referral_db.users.name</code>.
     */
    public void setName(String value);

    /**
     * Getter for <code>referral_db.users.name</code>.
     */
    public String getName();

    /**
     * Setter for <code>referral_db.users.email_id</code>.
     */
    public void setEmailId(String value);

    /**
     * Getter for <code>referral_db.users.email_id</code>.
     */
    public String getEmailId();

    /**
     * Setter for <code>referral_db.users.phone</code>.
     */
    public void setPhone(String value);

    /**
     * Getter for <code>referral_db.users.phone</code>.
     */
    public String getPhone();

    /**
     * Setter for <code>referral_db.users.password</code>.
     */
    public void setPassword(String value);

    /**
     * Getter for <code>referral_db.users.password</code>.
     */
    public String getPassword();

    /**
     * Setter for <code>referral_db.users.role</code>.
     */
    public void setRole(String value);

    /**
     * Getter for <code>referral_db.users.role</code>.
     */
    public String getRole();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common
     * interface IUsers
     */
    public void from(IUsers from);

    /**
     * Copy data into another generated Record/POJO implementing the common
     * interface IUsers
     */
    public <E extends IUsers> E into(E into);
}
