/*
 * This file is generated by jOOQ.
 */
package com.getReferral.Referral.Application.jooq.tables.pojos;


import com.getReferral.Referral.Application.jooq.tables.interfaces.IReferrer;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Referrer implements IReferrer {

    private static final long serialVersionUID = 1L;

    private Integer referrerId;
    private Integer userId;

    public Referrer() {}

    public Referrer(IReferrer value) {
        this.referrerId = value.getReferrerId();
        this.userId = value.getUserId();
    }

    public Referrer(
        Integer referrerId,
        Integer userId
    ) {
        this.referrerId = referrerId;
        this.userId = userId;
    }

    /**
     * Getter for <code>referral_db.referrer.referrer_id</code>.
     */
    @Override
    public Integer getReferrerId() {
        return this.referrerId;
    }

    /**
     * Setter for <code>referral_db.referrer.referrer_id</code>.
     */
    @Override
    public void setReferrerId(Integer referrerId) {
        this.referrerId = referrerId;
    }

    /**
     * Getter for <code>referral_db.referrer.user_id</code>.
     */
    @Override
    public Integer getUserId() {
        return this.userId;
    }

    /**
     * Setter for <code>referral_db.referrer.user_id</code>.
     */
    @Override
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Referrer other = (Referrer) obj;
        if (this.referrerId == null) {
            if (other.referrerId != null)
                return false;
        }
        else if (!this.referrerId.equals(other.referrerId))
            return false;
        if (this.userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!this.userId.equals(other.userId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.referrerId == null) ? 0 : this.referrerId.hashCode());
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Referrer (");

        sb.append(referrerId);
        sb.append(", ").append(userId);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IReferrer from) {
        setReferrerId(from.getReferrerId());
        setUserId(from.getUserId());
    }

    @Override
    public <E extends IReferrer> E into(E into) {
        into.from(this);
        return into;
    }
}
