/*
 * This file is generated by jOOQ.
 */
package com.getReferral.Referral.Application.jooq.tables.pojos;


import com.getReferral.Referral.Application.jooq.tables.interfaces.IReferralPosting;

import java.math.BigDecimal;
import java.time.LocalDate;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ReferralPosting implements IReferralPosting {

    private static final long serialVersionUID = 1L;

    private Integer referralPostingId;
    private Integer referrerId;
    private String referralPostingTitle;
    private String branch;
    private Integer passoutYr;
    private String expTitle;
    private String expTech;
    private String projectTech;
    private String techSkills;
    private String softSkills;
    private BigDecimal ctc;
    private Integer positions;
    private LocalDate lastDateToApply;
    private String companyName;
    private String referralPostingDesripation;

    public ReferralPosting() {}

    public ReferralPosting(IReferralPosting value) {
        this.referralPostingId = value.getReferralPostingId();
        this.referrerId = value.getReferrerId();
        this.referralPostingTitle = value.getReferralPostingTitle();
        this.branch = value.getBranch();
        this.passoutYr = value.getPassoutYr();
        this.expTitle = value.getExpTitle();
        this.expTech = value.getExpTech();
        this.projectTech = value.getProjectTech();
        this.techSkills = value.getTechSkills();
        this.softSkills = value.getSoftSkills();
        this.ctc = value.getCtc();
        this.positions = value.getPositions();
        this.lastDateToApply = value.getLastDateToApply();
        this.companyName = value.getCompanyName();
        this.referralPostingDesripation = value.getReferralPostingDesripation();
    }

    public ReferralPosting(
        Integer referralPostingId,
        Integer referrerId,
        String referralPostingTitle,
        String branch,
        Integer passoutYr,
        String expTitle,
        String expTech,
        String projectTech,
        String techSkills,
        String softSkills,
        BigDecimal ctc,
        Integer positions,
        LocalDate lastDateToApply,
        String companyName,
        String referralPostingDesripation
    ) {
        this.referralPostingId = referralPostingId;
        this.referrerId = referrerId;
        this.referralPostingTitle = referralPostingTitle;
        this.branch = branch;
        this.passoutYr = passoutYr;
        this.expTitle = expTitle;
        this.expTech = expTech;
        this.projectTech = projectTech;
        this.techSkills = techSkills;
        this.softSkills = softSkills;
        this.ctc = ctc;
        this.positions = positions;
        this.lastDateToApply = lastDateToApply;
        this.companyName = companyName;
        this.referralPostingDesripation = referralPostingDesripation;
    }

    /**
     * Getter for <code>referral_db.referral_posting.referral_posting_id</code>.
     */
    @Override
    public Integer getReferralPostingId() {
        return this.referralPostingId;
    }

    /**
     * Setter for <code>referral_db.referral_posting.referral_posting_id</code>.
     */
    @Override
    public void setReferralPostingId(Integer referralPostingId) {
        this.referralPostingId = referralPostingId;
    }

    /**
     * Getter for <code>referral_db.referral_posting.referrer_id</code>.
     */
    @Override
    public Integer getReferrerId() {
        return this.referrerId;
    }

    /**
     * Setter for <code>referral_db.referral_posting.referrer_id</code>.
     */
    @Override
    public void setReferrerId(Integer referrerId) {
        this.referrerId = referrerId;
    }

    /**
     * Getter for
     * <code>referral_db.referral_posting.referral_posting_title</code>.
     */
    @Override
    public String getReferralPostingTitle() {
        return this.referralPostingTitle;
    }

    /**
     * Setter for
     * <code>referral_db.referral_posting.referral_posting_title</code>.
     */
    @Override
    public void setReferralPostingTitle(String referralPostingTitle) {
        this.referralPostingTitle = referralPostingTitle;
    }

    /**
     * Getter for <code>referral_db.referral_posting.branch</code>.
     */
    @Override
    public String getBranch() {
        return this.branch;
    }

    /**
     * Setter for <code>referral_db.referral_posting.branch</code>.
     */
    @Override
    public void setBranch(String branch) {
        this.branch = branch;
    }

    /**
     * Getter for <code>referral_db.referral_posting.passout_yr</code>.
     */
    @Override
    public Integer getPassoutYr() {
        return this.passoutYr;
    }

    /**
     * Setter for <code>referral_db.referral_posting.passout_yr</code>.
     */
    @Override
    public void setPassoutYr(Integer passoutYr) {
        this.passoutYr = passoutYr;
    }

    /**
     * Getter for <code>referral_db.referral_posting.exp_title</code>.
     */
    @Override
    public String getExpTitle() {
        return this.expTitle;
    }

    /**
     * Setter for <code>referral_db.referral_posting.exp_title</code>.
     */
    @Override
    public void setExpTitle(String expTitle) {
        this.expTitle = expTitle;
    }

    /**
     * Getter for <code>referral_db.referral_posting.exp_tech</code>.
     */
    @Override
    public String getExpTech() {
        return this.expTech;
    }

    /**
     * Setter for <code>referral_db.referral_posting.exp_tech</code>.
     */
    @Override
    public void setExpTech(String expTech) {
        this.expTech = expTech;
    }

    /**
     * Getter for <code>referral_db.referral_posting.project_tech</code>.
     */
    @Override
    public String getProjectTech() {
        return this.projectTech;
    }

    /**
     * Setter for <code>referral_db.referral_posting.project_tech</code>.
     */
    @Override
    public void setProjectTech(String projectTech) {
        this.projectTech = projectTech;
    }

    /**
     * Getter for <code>referral_db.referral_posting.tech_skills</code>.
     */
    @Override
    public String getTechSkills() {
        return this.techSkills;
    }

    /**
     * Setter for <code>referral_db.referral_posting.tech_skills</code>.
     */
    @Override
    public void setTechSkills(String techSkills) {
        this.techSkills = techSkills;
    }

    /**
     * Getter for <code>referral_db.referral_posting.soft_skills</code>.
     */
    @Override
    public String getSoftSkills() {
        return this.softSkills;
    }

    /**
     * Setter for <code>referral_db.referral_posting.soft_skills</code>.
     */
    @Override
    public void setSoftSkills(String softSkills) {
        this.softSkills = softSkills;
    }

    /**
     * Getter for <code>referral_db.referral_posting.ctc</code>.
     */
    @Override
    public BigDecimal getCtc() {
        return this.ctc;
    }

    /**
     * Setter for <code>referral_db.referral_posting.ctc</code>.
     */
    @Override
    public void setCtc(BigDecimal ctc) {
        this.ctc = ctc;
    }

    /**
     * Getter for <code>referral_db.referral_posting.positions</code>.
     */
    @Override
    public Integer getPositions() {
        return this.positions;
    }

    /**
     * Setter for <code>referral_db.referral_posting.positions</code>.
     */
    @Override
    public void setPositions(Integer positions) {
        this.positions = positions;
    }

    /**
     * Getter for <code>referral_db.referral_posting.last_date_to_apply</code>.
     */
    @Override
    public LocalDate getLastDateToApply() {
        return this.lastDateToApply;
    }

    /**
     * Setter for <code>referral_db.referral_posting.last_date_to_apply</code>.
     */
    @Override
    public void setLastDateToApply(LocalDate lastDateToApply) {
        this.lastDateToApply = lastDateToApply;
    }

    /**
     * Getter for <code>referral_db.referral_posting.company_name</code>.
     */
    @Override
    public String getCompanyName() {
        return this.companyName;
    }

    /**
     * Setter for <code>referral_db.referral_posting.company_name</code>.
     */
    @Override
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    /**
     * Getter for
     * <code>referral_db.referral_posting.referral_posting_desripation</code>.
     */
    @Override
    public String getReferralPostingDesripation() {
        return this.referralPostingDesripation;
    }

    /**
     * Setter for
     * <code>referral_db.referral_posting.referral_posting_desripation</code>.
     */
    @Override
    public void setReferralPostingDesripation(String referralPostingDesripation) {
        this.referralPostingDesripation = referralPostingDesripation;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final ReferralPosting other = (ReferralPosting) obj;
        if (this.referralPostingId == null) {
            if (other.referralPostingId != null)
                return false;
        }
        else if (!this.referralPostingId.equals(other.referralPostingId))
            return false;
        if (this.referrerId == null) {
            if (other.referrerId != null)
                return false;
        }
        else if (!this.referrerId.equals(other.referrerId))
            return false;
        if (this.referralPostingTitle == null) {
            if (other.referralPostingTitle != null)
                return false;
        }
        else if (!this.referralPostingTitle.equals(other.referralPostingTitle))
            return false;
        if (this.branch == null) {
            if (other.branch != null)
                return false;
        }
        else if (!this.branch.equals(other.branch))
            return false;
        if (this.passoutYr == null) {
            if (other.passoutYr != null)
                return false;
        }
        else if (!this.passoutYr.equals(other.passoutYr))
            return false;
        if (this.expTitle == null) {
            if (other.expTitle != null)
                return false;
        }
        else if (!this.expTitle.equals(other.expTitle))
            return false;
        if (this.expTech == null) {
            if (other.expTech != null)
                return false;
        }
        else if (!this.expTech.equals(other.expTech))
            return false;
        if (this.projectTech == null) {
            if (other.projectTech != null)
                return false;
        }
        else if (!this.projectTech.equals(other.projectTech))
            return false;
        if (this.techSkills == null) {
            if (other.techSkills != null)
                return false;
        }
        else if (!this.techSkills.equals(other.techSkills))
            return false;
        if (this.softSkills == null) {
            if (other.softSkills != null)
                return false;
        }
        else if (!this.softSkills.equals(other.softSkills))
            return false;
        if (this.ctc == null) {
            if (other.ctc != null)
                return false;
        }
        else if (!this.ctc.equals(other.ctc))
            return false;
        if (this.positions == null) {
            if (other.positions != null)
                return false;
        }
        else if (!this.positions.equals(other.positions))
            return false;
        if (this.lastDateToApply == null) {
            if (other.lastDateToApply != null)
                return false;
        }
        else if (!this.lastDateToApply.equals(other.lastDateToApply))
            return false;
        if (this.companyName == null) {
            if (other.companyName != null)
                return false;
        }
        else if (!this.companyName.equals(other.companyName))
            return false;
        if (this.referralPostingDesripation == null) {
            if (other.referralPostingDesripation != null)
                return false;
        }
        else if (!this.referralPostingDesripation.equals(other.referralPostingDesripation))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.referralPostingId == null) ? 0 : this.referralPostingId.hashCode());
        result = prime * result + ((this.referrerId == null) ? 0 : this.referrerId.hashCode());
        result = prime * result + ((this.referralPostingTitle == null) ? 0 : this.referralPostingTitle.hashCode());
        result = prime * result + ((this.branch == null) ? 0 : this.branch.hashCode());
        result = prime * result + ((this.passoutYr == null) ? 0 : this.passoutYr.hashCode());
        result = prime * result + ((this.expTitle == null) ? 0 : this.expTitle.hashCode());
        result = prime * result + ((this.expTech == null) ? 0 : this.expTech.hashCode());
        result = prime * result + ((this.projectTech == null) ? 0 : this.projectTech.hashCode());
        result = prime * result + ((this.techSkills == null) ? 0 : this.techSkills.hashCode());
        result = prime * result + ((this.softSkills == null) ? 0 : this.softSkills.hashCode());
        result = prime * result + ((this.ctc == null) ? 0 : this.ctc.hashCode());
        result = prime * result + ((this.positions == null) ? 0 : this.positions.hashCode());
        result = prime * result + ((this.lastDateToApply == null) ? 0 : this.lastDateToApply.hashCode());
        result = prime * result + ((this.companyName == null) ? 0 : this.companyName.hashCode());
        result = prime * result + ((this.referralPostingDesripation == null) ? 0 : this.referralPostingDesripation.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ReferralPosting (");

        sb.append(referralPostingId);
        sb.append(", ").append(referrerId);
        sb.append(", ").append(referralPostingTitle);
        sb.append(", ").append(branch);
        sb.append(", ").append(passoutYr);
        sb.append(", ").append(expTitle);
        sb.append(", ").append(expTech);
        sb.append(", ").append(projectTech);
        sb.append(", ").append(techSkills);
        sb.append(", ").append(softSkills);
        sb.append(", ").append(ctc);
        sb.append(", ").append(positions);
        sb.append(", ").append(lastDateToApply);
        sb.append(", ").append(companyName);
        sb.append(", ").append(referralPostingDesripation);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IReferralPosting from) {
        setReferralPostingId(from.getReferralPostingId());
        setReferrerId(from.getReferrerId());
        setReferralPostingTitle(from.getReferralPostingTitle());
        setBranch(from.getBranch());
        setPassoutYr(from.getPassoutYr());
        setExpTitle(from.getExpTitle());
        setExpTech(from.getExpTech());
        setProjectTech(from.getProjectTech());
        setTechSkills(from.getTechSkills());
        setSoftSkills(from.getSoftSkills());
        setCtc(from.getCtc());
        setPositions(from.getPositions());
        setLastDateToApply(from.getLastDateToApply());
        setCompanyName(from.getCompanyName());
        setReferralPostingDesripation(from.getReferralPostingDesripation());
    }

    @Override
    public <E extends IReferralPosting> E into(E into) {
        into.from(this);
        return into;
    }
}
