/*
 * This file is generated by jOOQ.
 */
package com.getReferral.Referral.Application.jooq.tables.pojos;


import com.getReferral.Referral.Application.jooq.tables.interfaces.IReferralApplications;

import java.time.LocalDate;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ReferralApplications implements IReferralApplications {

    private static final long serialVersionUID = 1L;

    private Integer referralApplicationId;
    private Integer referralPostingId;
    private Integer referrerId;
    private Integer applicantId;
    private Integer resumeId;
    private LocalDate appliedDate;
    private String status;

    public ReferralApplications() {}

    public ReferralApplications(IReferralApplications value) {
        this.referralApplicationId = value.getReferralApplicationId();
        this.referralPostingId = value.getReferralPostingId();
        this.referrerId = value.getReferrerId();
        this.applicantId = value.getApplicantId();
        this.resumeId = value.getResumeId();
        this.appliedDate = value.getAppliedDate();
        this.status = value.getStatus();
    }

    public ReferralApplications(
        Integer referralApplicationId,
        Integer referralPostingId,
        Integer referrerId,
        Integer applicantId,
        Integer resumeId,
        LocalDate appliedDate,
        String status
    ) {
        this.referralApplicationId = referralApplicationId;
        this.referralPostingId = referralPostingId;
        this.referrerId = referrerId;
        this.applicantId = applicantId;
        this.resumeId = resumeId;
        this.appliedDate = appliedDate;
        this.status = status;
    }

    /**
     * Getter for
     * <code>referral_db.referral_applications.referral_application_id</code>.
     */
    @Override
    public Integer getReferralApplicationId() {
        return this.referralApplicationId;
    }

    /**
     * Setter for
     * <code>referral_db.referral_applications.referral_application_id</code>.
     */
    @Override
    public void setReferralApplicationId(Integer referralApplicationId) {
        this.referralApplicationId = referralApplicationId;
    }

    /**
     * Getter for
     * <code>referral_db.referral_applications.referral_posting_id</code>.
     */
    @Override
    public Integer getReferralPostingId() {
        return this.referralPostingId;
    }

    /**
     * Setter for
     * <code>referral_db.referral_applications.referral_posting_id</code>.
     */
    @Override
    public void setReferralPostingId(Integer referralPostingId) {
        this.referralPostingId = referralPostingId;
    }

    /**
     * Getter for <code>referral_db.referral_applications.referrer_id</code>.
     */
    @Override
    public Integer getReferrerId() {
        return this.referrerId;
    }

    /**
     * Setter for <code>referral_db.referral_applications.referrer_id</code>.
     */
    @Override
    public void setReferrerId(Integer referrerId) {
        this.referrerId = referrerId;
    }

    /**
     * Getter for <code>referral_db.referral_applications.applicant_id</code>.
     */
    @Override
    public Integer getApplicantId() {
        return this.applicantId;
    }

    /**
     * Setter for <code>referral_db.referral_applications.applicant_id</code>.
     */
    @Override
    public void setApplicantId(Integer applicantId) {
        this.applicantId = applicantId;
    }

    /**
     * Getter for <code>referral_db.referral_applications.resume_id</code>.
     */
    @Override
    public Integer getResumeId() {
        return this.resumeId;
    }

    /**
     * Setter for <code>referral_db.referral_applications.resume_id</code>.
     */
    @Override
    public void setResumeId(Integer resumeId) {
        this.resumeId = resumeId;
    }

    /**
     * Getter for <code>referral_db.referral_applications.applied_date</code>.
     */
    @Override
    public LocalDate getAppliedDate() {
        return this.appliedDate;
    }

    /**
     * Setter for <code>referral_db.referral_applications.applied_date</code>.
     */
    @Override
    public void setAppliedDate(LocalDate appliedDate) {
        this.appliedDate = appliedDate;
    }

    /**
     * Getter for <code>referral_db.referral_applications.status</code>.
     */
    @Override
    public String getStatus() {
        return this.status;
    }

    /**
     * Setter for <code>referral_db.referral_applications.status</code>.
     */
    @Override
    public void setStatus(String status) {
        this.status = status;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final ReferralApplications other = (ReferralApplications) obj;
        if (this.referralApplicationId == null) {
            if (other.referralApplicationId != null)
                return false;
        }
        else if (!this.referralApplicationId.equals(other.referralApplicationId))
            return false;
        if (this.referralPostingId == null) {
            if (other.referralPostingId != null)
                return false;
        }
        else if (!this.referralPostingId.equals(other.referralPostingId))
            return false;
        if (this.referrerId == null) {
            if (other.referrerId != null)
                return false;
        }
        else if (!this.referrerId.equals(other.referrerId))
            return false;
        if (this.applicantId == null) {
            if (other.applicantId != null)
                return false;
        }
        else if (!this.applicantId.equals(other.applicantId))
            return false;
        if (this.resumeId == null) {
            if (other.resumeId != null)
                return false;
        }
        else if (!this.resumeId.equals(other.resumeId))
            return false;
        if (this.appliedDate == null) {
            if (other.appliedDate != null)
                return false;
        }
        else if (!this.appliedDate.equals(other.appliedDate))
            return false;
        if (this.status == null) {
            if (other.status != null)
                return false;
        }
        else if (!this.status.equals(other.status))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.referralApplicationId == null) ? 0 : this.referralApplicationId.hashCode());
        result = prime * result + ((this.referralPostingId == null) ? 0 : this.referralPostingId.hashCode());
        result = prime * result + ((this.referrerId == null) ? 0 : this.referrerId.hashCode());
        result = prime * result + ((this.applicantId == null) ? 0 : this.applicantId.hashCode());
        result = prime * result + ((this.resumeId == null) ? 0 : this.resumeId.hashCode());
        result = prime * result + ((this.appliedDate == null) ? 0 : this.appliedDate.hashCode());
        result = prime * result + ((this.status == null) ? 0 : this.status.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ReferralApplications (");

        sb.append(referralApplicationId);
        sb.append(", ").append(referralPostingId);
        sb.append(", ").append(referrerId);
        sb.append(", ").append(applicantId);
        sb.append(", ").append(resumeId);
        sb.append(", ").append(appliedDate);
        sb.append(", ").append(status);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IReferralApplications from) {
        setReferralApplicationId(from.getReferralApplicationId());
        setReferralPostingId(from.getReferralPostingId());
        setReferrerId(from.getReferrerId());
        setApplicantId(from.getApplicantId());
        setResumeId(from.getResumeId());
        setAppliedDate(from.getAppliedDate());
        setStatus(from.getStatus());
    }

    @Override
    public <E extends IReferralApplications> E into(E into) {
        into.from(this);
        return into;
    }
}
