/*
 * This file is generated by jOOQ.
 */
package com.getReferral.Referral.Application.jooq.tables.pojos;


import com.getReferral.Referral.Application.jooq.tables.interfaces.IResumes;

import java.math.BigDecimal;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Resumes implements IResumes {

    private static final long serialVersionUID = 1L;

    private Integer resumeId;
    private Integer applicantId;
    private String resumeName;
    private String branch;
    private Integer passoutYr;
    private BigDecimal expDuration;

    public Resumes() {}

    public Resumes(IResumes value) {
        this.resumeId = value.getResumeId();
        this.applicantId = value.getApplicantId();
        this.resumeName = value.getResumeName();
        this.branch = value.getBranch();
        this.passoutYr = value.getPassoutYr();
        this.expDuration = value.getExpDuration();
    }

    public Resumes(
        Integer resumeId,
        Integer applicantId,
        String resumeName,
        String branch,
        Integer passoutYr,
        BigDecimal expDuration
    ) {
        this.resumeId = resumeId;
        this.applicantId = applicantId;
        this.resumeName = resumeName;
        this.branch = branch;
        this.passoutYr = passoutYr;
        this.expDuration = expDuration;
    }

    /**
     * Getter for <code>referral_db.resumes.resume_id</code>.
     */
    @Override
    public Integer getResumeId() {
        return this.resumeId;
    }

    /**
     * Setter for <code>referral_db.resumes.resume_id</code>.
     */
    @Override
    public void setResumeId(Integer resumeId) {
        this.resumeId = resumeId;
    }

    /**
     * Getter for <code>referral_db.resumes.applicant_id</code>.
     */
    @Override
    public Integer getApplicantId() {
        return this.applicantId;
    }

    /**
     * Setter for <code>referral_db.resumes.applicant_id</code>.
     */
    @Override
    public void setApplicantId(Integer applicantId) {
        this.applicantId = applicantId;
    }

    /**
     * Getter for <code>referral_db.resumes.resume_name</code>.
     */
    @Override
    public String getResumeName() {
        return this.resumeName;
    }

    /**
     * Setter for <code>referral_db.resumes.resume_name</code>.
     */
    @Override
    public void setResumeName(String resumeName) {
        this.resumeName = resumeName;
    }

    /**
     * Getter for <code>referral_db.resumes.branch</code>.
     */
    @Override
    public String getBranch() {
        return this.branch;
    }

    /**
     * Setter for <code>referral_db.resumes.branch</code>.
     */
    @Override
    public void setBranch(String branch) {
        this.branch = branch;
    }

    /**
     * Getter for <code>referral_db.resumes.passout_yr</code>.
     */
    @Override
    public Integer getPassoutYr() {
        return this.passoutYr;
    }

    /**
     * Setter for <code>referral_db.resumes.passout_yr</code>.
     */
    @Override
    public void setPassoutYr(Integer passoutYr) {
        this.passoutYr = passoutYr;
    }

    /**
     * Getter for <code>referral_db.resumes.exp_duration</code>.
     */
    @Override
    public BigDecimal getExpDuration() {
        return this.expDuration;
    }

    /**
     * Setter for <code>referral_db.resumes.exp_duration</code>.
     */
    @Override
    public void setExpDuration(BigDecimal expDuration) {
        this.expDuration = expDuration;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Resumes other = (Resumes) obj;
        if (this.resumeId == null) {
            if (other.resumeId != null)
                return false;
        }
        else if (!this.resumeId.equals(other.resumeId))
            return false;
        if (this.applicantId == null) {
            if (other.applicantId != null)
                return false;
        }
        else if (!this.applicantId.equals(other.applicantId))
            return false;
        if (this.resumeName == null) {
            if (other.resumeName != null)
                return false;
        }
        else if (!this.resumeName.equals(other.resumeName))
            return false;
        if (this.branch == null) {
            if (other.branch != null)
                return false;
        }
        else if (!this.branch.equals(other.branch))
            return false;
        if (this.passoutYr == null) {
            if (other.passoutYr != null)
                return false;
        }
        else if (!this.passoutYr.equals(other.passoutYr))
            return false;
        if (this.expDuration == null) {
            if (other.expDuration != null)
                return false;
        }
        else if (!this.expDuration.equals(other.expDuration))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.resumeId == null) ? 0 : this.resumeId.hashCode());
        result = prime * result + ((this.applicantId == null) ? 0 : this.applicantId.hashCode());
        result = prime * result + ((this.resumeName == null) ? 0 : this.resumeName.hashCode());
        result = prime * result + ((this.branch == null) ? 0 : this.branch.hashCode());
        result = prime * result + ((this.passoutYr == null) ? 0 : this.passoutYr.hashCode());
        result = prime * result + ((this.expDuration == null) ? 0 : this.expDuration.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Resumes (");

        sb.append(resumeId);
        sb.append(", ").append(applicantId);
        sb.append(", ").append(resumeName);
        sb.append(", ").append(branch);
        sb.append(", ").append(passoutYr);
        sb.append(", ").append(expDuration);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IResumes from) {
        setResumeId(from.getResumeId());
        setApplicantId(from.getApplicantId());
        setResumeName(from.getResumeName());
        setBranch(from.getBranch());
        setPassoutYr(from.getPassoutYr());
        setExpDuration(from.getExpDuration());
    }

    @Override
    public <E extends IResumes> E into(E into) {
        into.from(this);
        return into;
    }
}
