/*
 * This file is generated by jOOQ.
 */
package com.getReferral.Referral.Application.jooq.tables.pojos;


import com.getReferral.Referral.Application.jooq.tables.interfaces.IUsers;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Users implements IUsers {

    private static final long serialVersionUID = 1L;

    private Integer userId;
    private String name;
    private String emailId;
    private String phone;
    private String password;
    private String role;

    public Users() {}

    public Users(IUsers value) {
        this.userId = value.getUserId();
        this.name = value.getName();
        this.emailId = value.getEmailId();
        this.phone = value.getPhone();
        this.password = value.getPassword();
        this.role = value.getRole();
    }

    public Users(
        Integer userId,
        String name,
        String emailId,
        String phone,
        String password,
        String role
    ) {
        this.userId = userId;
        this.name = name;
        this.emailId = emailId;
        this.phone = phone;
        this.password = password;
        this.role = role;
    }

    /**
     * Getter for <code>referral_db.users.user_id</code>.
     */
    @Override
    public Integer getUserId() {
        return this.userId;
    }

    /**
     * Setter for <code>referral_db.users.user_id</code>.
     */
    @Override
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * Getter for <code>referral_db.users.name</code>.
     */
    @Override
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>referral_db.users.name</code>.
     */
    @Override
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for <code>referral_db.users.email_id</code>.
     */
    @Override
    public String getEmailId() {
        return this.emailId;
    }

    /**
     * Setter for <code>referral_db.users.email_id</code>.
     */
    @Override
    public void setEmailId(String emailId) {
        this.emailId = emailId;
    }

    /**
     * Getter for <code>referral_db.users.phone</code>.
     */
    @Override
    public String getPhone() {
        return this.phone;
    }

    /**
     * Setter for <code>referral_db.users.phone</code>.
     */
    @Override
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * Getter for <code>referral_db.users.password</code>.
     */
    @Override
    public String getPassword() {
        return this.password;
    }

    /**
     * Setter for <code>referral_db.users.password</code>.
     */
    @Override
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * Getter for <code>referral_db.users.role</code>.
     */
    @Override
    public String getRole() {
        return this.role;
    }

    /**
     * Setter for <code>referral_db.users.role</code>.
     */
    @Override
    public void setRole(String role) {
        this.role = role;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Users other = (Users) obj;
        if (this.userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!this.userId.equals(other.userId))
            return false;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        if (this.emailId == null) {
            if (other.emailId != null)
                return false;
        }
        else if (!this.emailId.equals(other.emailId))
            return false;
        if (this.phone == null) {
            if (other.phone != null)
                return false;
        }
        else if (!this.phone.equals(other.phone))
            return false;
        if (this.password == null) {
            if (other.password != null)
                return false;
        }
        else if (!this.password.equals(other.password))
            return false;
        if (this.role == null) {
            if (other.role != null)
                return false;
        }
        else if (!this.role.equals(other.role))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.emailId == null) ? 0 : this.emailId.hashCode());
        result = prime * result + ((this.phone == null) ? 0 : this.phone.hashCode());
        result = prime * result + ((this.password == null) ? 0 : this.password.hashCode());
        result = prime * result + ((this.role == null) ? 0 : this.role.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Users (");

        sb.append(userId);
        sb.append(", ").append(name);
        sb.append(", ").append(emailId);
        sb.append(", ").append(phone);
        sb.append(", ").append(password);
        sb.append(", ").append(role);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IUsers from) {
        setUserId(from.getUserId());
        setName(from.getName());
        setEmailId(from.getEmailId());
        setPhone(from.getPhone());
        setPassword(from.getPassword());
        setRole(from.getRole());
    }

    @Override
    public <E extends IUsers> E into(E into) {
        into.from(this);
        return into;
    }
}
