/*
 * This file is generated by jOOQ.
 */
package com.getReferral.Referral.Application.jooq.tables;


import com.getReferral.Referral.Application.jooq.Keys;
import com.getReferral.Referral.Application.jooq.ReferralDb;
import com.getReferral.Referral.Application.jooq.tables.ReferralApplications.ReferralApplicationsPath;
import com.getReferral.Referral.Application.jooq.tables.Resumes.ResumesPath;
import com.getReferral.Referral.Application.jooq.tables.Users.UsersPath;
import com.getReferral.Referral.Application.jooq.tables.records.ApplicantsRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Applicants extends TableImpl<ApplicantsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>referral_db.applicants</code>
     */
    public static final Applicants APPLICANTS = new Applicants();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ApplicantsRecord> getRecordType() {
        return ApplicantsRecord.class;
    }

    /**
     * The column <code>referral_db.applicants.applicant_id</code>.
     */
    public final TableField<ApplicantsRecord, Integer> APPLICANT_ID = createField(DSL.name("applicant_id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>referral_db.applicants.user_id</code>.
     */
    public final TableField<ApplicantsRecord, Integer> USER_ID = createField(DSL.name("user_id"), SQLDataType.INTEGER, this, "");

    private Applicants(Name alias, Table<ApplicantsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Applicants(Name alias, Table<ApplicantsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>referral_db.applicants</code> table reference
     */
    public Applicants(String alias) {
        this(DSL.name(alias), APPLICANTS);
    }

    /**
     * Create an aliased <code>referral_db.applicants</code> table reference
     */
    public Applicants(Name alias) {
        this(alias, APPLICANTS);
    }

    /**
     * Create a <code>referral_db.applicants</code> table reference
     */
    public Applicants() {
        this(DSL.name("applicants"), null);
    }

    public <O extends Record> Applicants(Table<O> path, ForeignKey<O, ApplicantsRecord> childPath, InverseForeignKey<O, ApplicantsRecord> parentPath) {
        super(path, childPath, parentPath, APPLICANTS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ApplicantsPath extends Applicants implements Path<ApplicantsRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ApplicantsPath(Table<O> path, ForeignKey<O, ApplicantsRecord> childPath, InverseForeignKey<O, ApplicantsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ApplicantsPath(Name alias, Table<ApplicantsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ApplicantsPath as(String alias) {
            return new ApplicantsPath(DSL.name(alias), this);
        }

        @Override
        public ApplicantsPath as(Name alias) {
            return new ApplicantsPath(alias, this);
        }

        @Override
        public ApplicantsPath as(Table<?> alias) {
            return new ApplicantsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : ReferralDb.REFERRAL_DB;
    }

    @Override
    public Identity<ApplicantsRecord, Integer> getIdentity() {
        return (Identity<ApplicantsRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<ApplicantsRecord> getPrimaryKey() {
        return Keys.KEY_APPLICANTS_PRIMARY;
    }

    @Override
    public List<UniqueKey<ApplicantsRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_APPLICANTS_USER_ID);
    }

    @Override
    public List<ForeignKey<ApplicantsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.APPLICANTS_IBFK_1);
    }

    private transient UsersPath _users;

    /**
     * Get the implicit join path to the <code>referral_db.users</code> table.
     */
    public UsersPath users() {
        if (_users == null)
            _users = new UsersPath(this, Keys.APPLICANTS_IBFK_1, null);

        return _users;
    }

    private transient ReferralApplicationsPath _referralApplications;

    /**
     * Get the implicit to-many join path to the
     * <code>referral_db.referral_applications</code> table
     */
    public ReferralApplicationsPath referralApplications() {
        if (_referralApplications == null)
            _referralApplications = new ReferralApplicationsPath(this, null, Keys.REFERRAL_APPLICATIONS_IBFK_1.getInverseKey());

        return _referralApplications;
    }

    private transient ResumesPath _resumes;

    /**
     * Get the implicit to-many join path to the
     * <code>referral_db.resumes</code> table
     */
    public ResumesPath resumes() {
        if (_resumes == null)
            _resumes = new ResumesPath(this, null, Keys.RESUMES_IBFK_1.getInverseKey());

        return _resumes;
    }

    @Override
    public Applicants as(String alias) {
        return new Applicants(DSL.name(alias), this);
    }

    @Override
    public Applicants as(Name alias) {
        return new Applicants(alias, this);
    }

    @Override
    public Applicants as(Table<?> alias) {
        return new Applicants(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Applicants rename(String name) {
        return new Applicants(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Applicants rename(Name name) {
        return new Applicants(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Applicants rename(Table<?> name) {
        return new Applicants(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Applicants where(Condition condition) {
        return new Applicants(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Applicants where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Applicants where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Applicants where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Applicants where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Applicants where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Applicants where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Applicants where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Applicants whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Applicants whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
