/*
 * This file is generated by jOOQ.
 */
package com.getReferral.Referral.Application.jooq.tables.records;


import com.getReferral.Referral.Application.jooq.tables.ReferralPosting;
import com.getReferral.Referral.Application.jooq.tables.interfaces.IReferralPosting;

import java.math.BigDecimal;
import java.time.LocalDate;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ReferralPostingRecord extends UpdatableRecordImpl<ReferralPostingRecord> implements IReferralPosting {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>referral_db.referral_posting.referral_posting_id</code>.
     */
    @Override
    public void setReferralPostingId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>referral_db.referral_posting.referral_posting_id</code>.
     */
    @Override
    public Integer getReferralPostingId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>referral_db.referral_posting.referrer_id</code>.
     */
    @Override
    public void setReferrerId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>referral_db.referral_posting.referrer_id</code>.
     */
    @Override
    public Integer getReferrerId() {
        return (Integer) get(1);
    }

    /**
     * Setter for
     * <code>referral_db.referral_posting.referral_posting_title</code>.
     */
    @Override
    public void setReferralPostingTitle(String value) {
        set(2, value);
    }

    /**
     * Getter for
     * <code>referral_db.referral_posting.referral_posting_title</code>.
     */
    @Override
    public String getReferralPostingTitle() {
        return (String) get(2);
    }

    /**
     * Setter for <code>referral_db.referral_posting.branch</code>.
     */
    @Override
    public void setBranch(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>referral_db.referral_posting.branch</code>.
     */
    @Override
    public String getBranch() {
        return (String) get(3);
    }

    /**
     * Setter for <code>referral_db.referral_posting.passout_yr</code>.
     */
    @Override
    public void setPassoutYr(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>referral_db.referral_posting.passout_yr</code>.
     */
    @Override
    public Integer getPassoutYr() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>referral_db.referral_posting.exp_title</code>.
     */
    @Override
    public void setExpTitle(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>referral_db.referral_posting.exp_title</code>.
     */
    @Override
    public String getExpTitle() {
        return (String) get(5);
    }

    /**
     * Setter for <code>referral_db.referral_posting.exp_tech</code>.
     */
    @Override
    public void setExpTech(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>referral_db.referral_posting.exp_tech</code>.
     */
    @Override
    public String getExpTech() {
        return (String) get(6);
    }

    /**
     * Setter for <code>referral_db.referral_posting.project_tech</code>.
     */
    @Override
    public void setProjectTech(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>referral_db.referral_posting.project_tech</code>.
     */
    @Override
    public String getProjectTech() {
        return (String) get(7);
    }

    /**
     * Setter for <code>referral_db.referral_posting.tech_skills</code>.
     */
    @Override
    public void setTechSkills(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>referral_db.referral_posting.tech_skills</code>.
     */
    @Override
    public String getTechSkills() {
        return (String) get(8);
    }

    /**
     * Setter for <code>referral_db.referral_posting.soft_skills</code>.
     */
    @Override
    public void setSoftSkills(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>referral_db.referral_posting.soft_skills</code>.
     */
    @Override
    public String getSoftSkills() {
        return (String) get(9);
    }

    /**
     * Setter for <code>referral_db.referral_posting.ctc</code>.
     */
    @Override
    public void setCtc(BigDecimal value) {
        set(10, value);
    }

    /**
     * Getter for <code>referral_db.referral_posting.ctc</code>.
     */
    @Override
    public BigDecimal getCtc() {
        return (BigDecimal) get(10);
    }

    /**
     * Setter for <code>referral_db.referral_posting.positions</code>.
     */
    @Override
    public void setPositions(Integer value) {
        set(11, value);
    }

    /**
     * Getter for <code>referral_db.referral_posting.positions</code>.
     */
    @Override
    public Integer getPositions() {
        return (Integer) get(11);
    }

    /**
     * Setter for <code>referral_db.referral_posting.last_date_to_apply</code>.
     */
    @Override
    public void setLastDateToApply(LocalDate value) {
        set(12, value);
    }

    /**
     * Getter for <code>referral_db.referral_posting.last_date_to_apply</code>.
     */
    @Override
    public LocalDate getLastDateToApply() {
        return (LocalDate) get(12);
    }

    /**
     * Setter for <code>referral_db.referral_posting.company_name</code>.
     */
    @Override
    public void setCompanyName(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>referral_db.referral_posting.company_name</code>.
     */
    @Override
    public String getCompanyName() {
        return (String) get(13);
    }

    /**
     * Setter for
     * <code>referral_db.referral_posting.referral_posting_desripation</code>.
     */
    @Override
    public void setReferralPostingDesripation(String value) {
        set(14, value);
    }

    /**
     * Getter for
     * <code>referral_db.referral_posting.referral_posting_desripation</code>.
     */
    @Override
    public String getReferralPostingDesripation() {
        return (String) get(14);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IReferralPosting from) {
        setReferralPostingId(from.getReferralPostingId());
        setReferrerId(from.getReferrerId());
        setReferralPostingTitle(from.getReferralPostingTitle());
        setBranch(from.getBranch());
        setPassoutYr(from.getPassoutYr());
        setExpTitle(from.getExpTitle());
        setExpTech(from.getExpTech());
        setProjectTech(from.getProjectTech());
        setTechSkills(from.getTechSkills());
        setSoftSkills(from.getSoftSkills());
        setCtc(from.getCtc());
        setPositions(from.getPositions());
        setLastDateToApply(from.getLastDateToApply());
        setCompanyName(from.getCompanyName());
        setReferralPostingDesripation(from.getReferralPostingDesripation());
        resetChangedOnNotNull();
    }

    @Override
    public <E extends IReferralPosting> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ReferralPostingRecord
     */
    public ReferralPostingRecord() {
        super(ReferralPosting.REFERRAL_POSTING);
    }

    /**
     * Create a detached, initialised ReferralPostingRecord
     */
    public ReferralPostingRecord(Integer referralPostingId, Integer referrerId, String referralPostingTitle, String branch, Integer passoutYr, String expTitle, String expTech, String projectTech, String techSkills, String softSkills, BigDecimal ctc, Integer positions, LocalDate lastDateToApply, String companyName, String referralPostingDesripation) {
        super(ReferralPosting.REFERRAL_POSTING);

        setReferralPostingId(referralPostingId);
        setReferrerId(referrerId);
        setReferralPostingTitle(referralPostingTitle);
        setBranch(branch);
        setPassoutYr(passoutYr);
        setExpTitle(expTitle);
        setExpTech(expTech);
        setProjectTech(projectTech);
        setTechSkills(techSkills);
        setSoftSkills(softSkills);
        setCtc(ctc);
        setPositions(positions);
        setLastDateToApply(lastDateToApply);
        setCompanyName(companyName);
        setReferralPostingDesripation(referralPostingDesripation);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised ReferralPostingRecord
     */
    public ReferralPostingRecord(com.getReferral.Referral.Application.jooq.tables.pojos.ReferralPosting value) {
        super(ReferralPosting.REFERRAL_POSTING);

        if (value != null) {
            setReferralPostingId(value.getReferralPostingId());
            setReferrerId(value.getReferrerId());
            setReferralPostingTitle(value.getReferralPostingTitle());
            setBranch(value.getBranch());
            setPassoutYr(value.getPassoutYr());
            setExpTitle(value.getExpTitle());
            setExpTech(value.getExpTech());
            setProjectTech(value.getProjectTech());
            setTechSkills(value.getTechSkills());
            setSoftSkills(value.getSoftSkills());
            setCtc(value.getCtc());
            setPositions(value.getPositions());
            setLastDateToApply(value.getLastDateToApply());
            setCompanyName(value.getCompanyName());
            setReferralPostingDesripation(value.getReferralPostingDesripation());
            resetChangedOnNotNull();
        }
    }
}
