/*
 * This file is generated by jOOQ.
 */
package com.getReferral.Referral.Application.jooq.tables.records;


import com.getReferral.Referral.Application.jooq.tables.ReferralApplications;
import com.getReferral.Referral.Application.jooq.tables.interfaces.IReferralApplications;

import java.time.LocalDate;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ReferralApplicationsRecord extends UpdatableRecordImpl<ReferralApplicationsRecord> implements IReferralApplications {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for
     * <code>referral_db.referral_applications.referral_application_id</code>.
     */
    @Override
    public void setReferralApplicationId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for
     * <code>referral_db.referral_applications.referral_application_id</code>.
     */
    @Override
    public Integer getReferralApplicationId() {
        return (Integer) get(0);
    }

    /**
     * Setter for
     * <code>referral_db.referral_applications.referral_posting_id</code>.
     */
    @Override
    public void setReferralPostingId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for
     * <code>referral_db.referral_applications.referral_posting_id</code>.
     */
    @Override
    public Integer getReferralPostingId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>referral_db.referral_applications.referrer_id</code>.
     */
    @Override
    public void setReferrerId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>referral_db.referral_applications.referrer_id</code>.
     */
    @Override
    public Integer getReferrerId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>referral_db.referral_applications.applicant_id</code>.
     */
    @Override
    public void setApplicantId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>referral_db.referral_applications.applicant_id</code>.
     */
    @Override
    public Integer getApplicantId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>referral_db.referral_applications.resume_id</code>.
     */
    @Override
    public void setResumeId(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>referral_db.referral_applications.resume_id</code>.
     */
    @Override
    public Integer getResumeId() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>referral_db.referral_applications.applied_date</code>.
     */
    @Override
    public void setAppliedDate(LocalDate value) {
        set(5, value);
    }

    /**
     * Getter for <code>referral_db.referral_applications.applied_date</code>.
     */
    @Override
    public LocalDate getAppliedDate() {
        return (LocalDate) get(5);
    }

    /**
     * Setter for <code>referral_db.referral_applications.status</code>.
     */
    @Override
    public void setStatus(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>referral_db.referral_applications.status</code>.
     */
    @Override
    public String getStatus() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IReferralApplications from) {
        setReferralApplicationId(from.getReferralApplicationId());
        setReferralPostingId(from.getReferralPostingId());
        setReferrerId(from.getReferrerId());
        setApplicantId(from.getApplicantId());
        setResumeId(from.getResumeId());
        setAppliedDate(from.getAppliedDate());
        setStatus(from.getStatus());
        resetChangedOnNotNull();
    }

    @Override
    public <E extends IReferralApplications> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ReferralApplicationsRecord
     */
    public ReferralApplicationsRecord() {
        super(ReferralApplications.REFERRAL_APPLICATIONS);
    }

    /**
     * Create a detached, initialised ReferralApplicationsRecord
     */
    public ReferralApplicationsRecord(Integer referralApplicationId, Integer referralPostingId, Integer referrerId, Integer applicantId, Integer resumeId, LocalDate appliedDate, String status) {
        super(ReferralApplications.REFERRAL_APPLICATIONS);

        setReferralApplicationId(referralApplicationId);
        setReferralPostingId(referralPostingId);
        setReferrerId(referrerId);
        setApplicantId(applicantId);
        setResumeId(resumeId);
        setAppliedDate(appliedDate);
        setStatus(status);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised ReferralApplicationsRecord
     */
    public ReferralApplicationsRecord(com.getReferral.Referral.Application.jooq.tables.pojos.ReferralApplications value) {
        super(ReferralApplications.REFERRAL_APPLICATIONS);

        if (value != null) {
            setReferralApplicationId(value.getReferralApplicationId());
            setReferralPostingId(value.getReferralPostingId());
            setReferrerId(value.getReferrerId());
            setApplicantId(value.getApplicantId());
            setResumeId(value.getResumeId());
            setAppliedDate(value.getAppliedDate());
            setStatus(value.getStatus());
            resetChangedOnNotNull();
        }
    }
}
