/*
 * This file is generated by jOOQ.
 */
package com.getReferral.Referral.Application.jooq.tables.records;


import com.getReferral.Referral.Application.jooq.tables.Resumes;
import com.getReferral.Referral.Application.jooq.tables.interfaces.IResumes;

import java.math.BigDecimal;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ResumesRecord extends UpdatableRecordImpl<ResumesRecord> implements IResumes {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>referral_db.resumes.resume_id</code>.
     */
    @Override
    public void setResumeId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>referral_db.resumes.resume_id</code>.
     */
    @Override
    public Integer getResumeId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>referral_db.resumes.applicant_id</code>.
     */
    @Override
    public void setApplicantId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>referral_db.resumes.applicant_id</code>.
     */
    @Override
    public Integer getApplicantId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>referral_db.resumes.resume_name</code>.
     */
    @Override
    public void setResumeName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>referral_db.resumes.resume_name</code>.
     */
    @Override
    public String getResumeName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>referral_db.resumes.branch</code>.
     */
    @Override
    public void setBranch(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>referral_db.resumes.branch</code>.
     */
    @Override
    public String getBranch() {
        return (String) get(3);
    }

    /**
     * Setter for <code>referral_db.resumes.passout_yr</code>.
     */
    @Override
    public void setPassoutYr(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>referral_db.resumes.passout_yr</code>.
     */
    @Override
    public Integer getPassoutYr() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>referral_db.resumes.exp_duration</code>.
     */
    @Override
    public void setExpDuration(BigDecimal value) {
        set(5, value);
    }

    /**
     * Getter for <code>referral_db.resumes.exp_duration</code>.
     */
    @Override
    public BigDecimal getExpDuration() {
        return (BigDecimal) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IResumes from) {
        setResumeId(from.getResumeId());
        setApplicantId(from.getApplicantId());
        setResumeName(from.getResumeName());
        setBranch(from.getBranch());
        setPassoutYr(from.getPassoutYr());
        setExpDuration(from.getExpDuration());
        resetChangedOnNotNull();
    }

    @Override
    public <E extends IResumes> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ResumesRecord
     */
    public ResumesRecord() {
        super(Resumes.RESUMES);
    }

    /**
     * Create a detached, initialised ResumesRecord
     */
    public ResumesRecord(Integer resumeId, Integer applicantId, String resumeName, String branch, Integer passoutYr, BigDecimal expDuration) {
        super(Resumes.RESUMES);

        setResumeId(resumeId);
        setApplicantId(applicantId);
        setResumeName(resumeName);
        setBranch(branch);
        setPassoutYr(passoutYr);
        setExpDuration(expDuration);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised ResumesRecord
     */
    public ResumesRecord(com.getReferral.Referral.Application.jooq.tables.pojos.Resumes value) {
        super(Resumes.RESUMES);

        if (value != null) {
            setResumeId(value.getResumeId());
            setApplicantId(value.getApplicantId());
            setResumeName(value.getResumeName());
            setBranch(value.getBranch());
            setPassoutYr(value.getPassoutYr());
            setExpDuration(value.getExpDuration());
            resetChangedOnNotNull();
        }
    }
}
